version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "2222:2222"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web
    restart: unless-stopped

  web:
    container_name: qbt-server
    build: .
    ports:
      - "1234:1234"
    # environment:
    #   - FLASK_DEBUG=True
    command: sh -c "/server/entrypoint.sh"
    restart: always
    volumes:
      - ./server:/server
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: qbt_db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # healthcheck:
    #   test: pg_isready -U postgres -d qbt_farm
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

volumes:
  postgres-data: {}
