version: '3'
services:
  web:
    container_name: qbt-server
    build: .
    ports:
      - "1234:1234"
    environment:
      - FLASK_DEBUG=True
    command: sh -c "FLASK_APP=/server/standalone.py FLASK_DEBUG=True python3 -m flask run --host 0.0.0.0 --port 1234 --with-threads"


  

