version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "2222:2222"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web
    restart: unless-stopped

  web:
    container_name: qbt-server
    build: .
    expose:
      - "1234"
    command:
      [
        "/server/entrypoint.sh",
        "qbt_db",
        "5432",
        "--",
        "sh",
        "-c",
        "FLASK_APP=/server/standalone.py python3 -m flask run --host 0.0.0.0 --port 1234 --with-threads"
      ]
    restart: always
    volumes:
      - ./server:/server
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: qbt_db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data: {}
